# Generated by Django 4.2.7 on 2023-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr_app', '0002_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('DISP', 'Disponible'), ('PRES', 'Prestado')], max_length=4),
        ),
    ]
