# Generated by Django 4.2.7 on 2023-12-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr_app', '0003_alter_libro_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
